<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
شکلات‌های خوب‌تر
</font>
</h1>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
فرض کنید که بعد از میل کردن چند شکلات معمولی (غیر دارک) متوجه شده‌ایم که بسیاری از آن‌ها هم خوشمزه هستند و اگر بتوانیم موارد با کیفیت‌تر آن‌ها را پیدا کنیم احتمالاً فروش خوبی خواهند داشت. پس در گام آخر از پروژه می‌خواهیم شرکت‌هایی که شکلات‌های باکیفیت‌تری را تولید می‌کنند شناسایی کرده و شکلات‌های ‌‌آن‌ها را جدا کنیم.
</font>
</p>


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در گام پیشین قیمت شکلات‌ها را تخمین زده و دیتافریم نهایی را در فایلی به نام <code>chocolate_price.csv</code> ذخیره کردید. در ابتدا آن فایل را به شکل یک دیتافریم بخوانید.
</font>
</p>


In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('chocolet_price.csv')
df.head()

,Unnamed: 0,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
توجه داشته باشید که در این گام تنها با شکلات‌های غیرتلخ کار داریم. پس در ابتدا تنها شکلات‌هایی که درصد کاکائوی آن‌ها کمتر یا مساوی  ۷۰ درصد است را جدا کرده و در دیتافریم <code>df</code> ذخیره کنید.
</font>
</p>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از جداسازی و ساخت دیتافریم، به کمک تابع <code dir=ltr>reset_index()</code> نمایه‌ها را ریست کنید. در این مرحله به آرگومان‌های <code>inplace</code> و <code>drop</code> هم توجه کنید.
</font>
</p>

In [17]:
print(df.columns)

Index(['Unnamed: 0', 'Company', 'Specific Bean Origin', 'Review Date',
       'Cocoa Percent', 'Company Location', 'Rating', 'Bean Type',
       'Broad Bean Origin', 'price(100g)'],
      dtype='object')


In [2]:
df1 = df[df['Cocoa Percent']<=70]
df1.reset_index()

df1.head()

,Unnamed: 0,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این قسمت به ازای هر شرکت شکلات‌سازی، میانگین امتیاز شکلات‌های آن را برای هر سال محاسبه کرده و همچون جدول زیر در دیتافریم <code>companies</code> ذخیره کنید.

<center>

| | 2006 | ... | 2015 | 2016 | 2017 |
| :---: | :---: | :---: | :---: | :---: | :---: |
| A. Morin | NaN | ... | 63.75 | 75.0 | NaN |
| ... | ... | ... | ... | ... | ...  |
| hexx | NaN | ... | 60.00 | NaN | NaN |
| twenty-four blackbirds | NaN | ... | NaN | NaN | NaN |

</center>
</font>
</p>



In [3]:
companies = df1.groupby(['Company','Review Date'])['Rating'].mean()
companiesdf= companies.unstack()
companiesdf

Review Date,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Company,,,,,,,,,,,,
A. Morin,NaN,NaN,NaN,NaN,NaN,NaN,72.500000,66.363636,70.0,63.75,75.0,NaN
AMMA,NaN,NaN,NaN,NaN,77.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Acalli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN
Adi,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN
Aequare (Gianduja),NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
Zokoko,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,65.0,NaN
Zotter,NaN,NaN,NaN,NaN,60.0,67.5,69.285714,NaN,NaN,NaN,NaN,NaN
hello cocoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.00,NaN,NaN


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
خطوط زیر برای استانداردسازی شکل جدول اعمال می‌شوند. این خطوط را تغییر نداده و تنها سلول زیر را اجرا کنید.
</font>
</p>

In [4]:
companiesdf.columns.name = None
companiesdf.index.name = None
companiesdf

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
A. Morin,NaN,NaN,NaN,NaN,NaN,NaN,72.500000,66.363636,70.0,63.75,75.0,NaN
AMMA,NaN,NaN,NaN,NaN,77.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Acalli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN
Adi,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN
Aequare (Gianduja),NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
Zokoko,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,65.0,NaN
Zotter,NaN,NaN,NaN,NaN,60.0,67.5,69.285714,NaN,NaN,NaN,NaN,NaN
hello cocoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.00,NaN,NaN
hexx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.00,NaN,NaN


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت سوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
برای پیدا کردن بهترین شرکت‌ها می‌خواهیم تنها امتیاز سال‌های ۲۰۱۲ به بعد را در نظر بگیریم (خود سال ۲۰۱۲ را هم در نظر بگیرید).
ابتدا به ازای هر کمپانی، میانگین امتیاز سال‌های ۲۰۱۲ به بعد آن را محاسبه کرده و در متغیر <code>mean_ratings</code> ذخیره کنید.
توجه داشته باشید که خروجی شما باید یک سری پانداز (<code>pd.Series</code>) باشد.
</font>
</p>


In [5]:
# "First solusion gives a data frame"
# columns_to_drop=[2006,2007,2008,2009,2010,2011]
# mean_ratings = companiesdf.drop(columns_to_drop,axis=1)
# mean_ratings['mean_rating']= mean_ratings.mean(axis=1,skipna=True)
# mean_ratings

mean_ratings=companiesdf[[2012,2013,2014,2015,2016,2017]].mean(axis=1,skipna=True)
# mean_ratings=companiesdf.apply(lambda x:x.mean(axis=1,skipna=True) if x>2011 else x, axis=1)
mean_ratings

A. Morin                  69.522727
AMMA                            NaN
Acalli                    75.000000
Adi                             NaN
Aequare (Gianduja)              NaN
                            ...    
Zokoko                    65.000000
Zotter                    69.285714
hello cocoa               55.000000
hexx                      60.000000
twenty-four blackbirds    65.000000
Length: 313, dtype: float64

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
اکنون به کمک میانگین امتیاز هر کمپانی (<code>mean_ratings</code>)، ۱۰ کمپانی با بهترین امتیاز را پیدا کنید و در متغیر <code>best_ratings</code> ذخیره کنید. توجه داشته باشید که خروجی شما باید یک سری پانداز (<code>pd.Series</code>) باشد.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:purple"><b>توجه:</b></span>
در مواردی که امتیاز کمپانی‌ها یکسان باشد، باید کمپانی را براساس ترتیب حروف الفبا انتخاب کنید. به‌عنوان مثال اگر دو کمپانی <code>A</code> و <code>B</code> هر دو میانگین امتیاز <code>75.00</code> داشته باشند، اولویت با شرکت <code>A</code> است.
</font>
</p>

In [10]:
best_ratings = mean_ratings.reset_index(name='mean_rating')
best_ratings = best_ratings.rename(columns={'index':'company'})


best_ratings= best_ratings.sort_values(by=['mean_rating','company'],ascending=[False,True])
best_ratings=best_ratings.head(10)
best_ratings

,company,mean_rating
224,Patric,80.000000
288,Tobago Estate (Pralus),80.000000
302,Willie's Cacao,80.000000
152,L.A. Burdick (Felchlin),77.500000
179,Matale,77.500000
219,Pacari,77.500000
293,Valrhona,76.666667
2,Acalli,75.000000
12,Amedei,75.000000
14,Askinosie,75.000000


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت چهارم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
اکنون شکلات‌هایی که کمپانی سازنده‌شان جزو ۱۰ شرکت برتر (<code>best_ratings</code>) است را از دیتافریم <code>df</code> انتخاب کرده و در دیتافریم <code>chocolates_to_sell</code> ذخیره کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی ۱:</b></span>
بعد از انتخاب این شکلات‌ها، به‌کمک دستور <code>reset_index</code> نمایه‌ها را ریست کنید. استفاده از آرگومان <code>drop</code> را نیز فراموش نکنید.

<br>
<span style="color:green"><b>راهنمایی ۲:</b></span>
برای بررسی وجود یک متغیر در یک لیست می‌توانید از تابع <code>isin</code> استفاده کنید.
</font>
</p>

In [ ]:
top_ten=best_ratings['company'].tolist()
chocolates_to_sell = df[df['Company'].isin(top_ten)]
chocolates_to_sell=chocolates_to_sell.reset_index(drop=False)
chocolates_to_sell

,index,Unnamed: 0,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,23,23,Acalli,"Chulucanas, El Platanal",2015,70.0,U.S.A.,75.0,Blend,Peru,131250.0
1,24,24,Acalli,"Tumbes, Norandino",2015,70.0,U.S.A.,75.0,Criollo,Peru,131250.0
2,75,75,Amedei,"Piura, Blanco de Criollo",2012,70.0,Italy,75.0,Blend,Peru,131250.0
3,76,76,Amedei,Porcelana,2007,70.0,Italy,80.0,Criollo (Porcelana),Venezuela,140000.0
4,77,77,Amedei,Nine,2007,75.0,Italy,80.0,Blend,Other,150000.0
...,...,...,...,...,...,...,...,...,...,...,...
78,1742,1742,Willie's Cacao,Sambirano,2010,71.0,U.K.,60.0,Trinitario,Madagascar,106500.0
79,1743,1743,Willie's Cacao,Hacienda Las Trincheras,2010,72.0,U.K.,70.0,Blend,Venezuela,126000.0
80,1744,1744,Willie's Cacao,Java,2010,69.0,U.K.,75.0,Blend,Indonesia,129375.0
81,1745,1745,Willie's Cacao,San Martin,2009,70.0,U.K.,60.0,Blend,Peru,105000.0


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت پنجم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در نهایت مجموع قیمت این شکلات‌ها (<code>chocolates_to_sell</code>) را در متغیر <code>priceSum</code> ذخیره کنید تا مجموع دریافتی ما از این شکلات‌ها هم مشخص شود.
</font>
</p>

In [13]:
priceSum = chocolates_to_sell['price(100g)'].sum()
print(f"the total price is: {priceSum}")

the total price is: 10149875.0
